try :
    print(x)
except as err:
    print("Print exception if error")